#!/usr/bin/env python3
"""Generate Gate I confirmatory run cards and Mac preflight cards from the frozen budget.

Do not hand-edit the generated files. Re-run this script after a budget change.
This script does not train and does not start official Gate I.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUDGET = json.loads((ROOT / "manifests" / "budget_manifest.json").read_text(encoding="utf-8"))
SPLIT = json.loads((ROOT / "manifests" / "split_manifest.json").read_text(encoding="utf-8"))
TOKENIZER = json.loads((ROOT / "manifests" / "tokenizer_manifest.json").read_text(encoding="utf-8"))

RUN_ID = BUDGET["run_id"]
NANOCHAT_COMMIT = "92d63d4e8bb4df75c3b71618f31ddde2378b2bcd"
OUT_DIR = ROOT / "docs" / "run-cards" / "gate-i"


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")
    return sha256_text(text)


def confirmatory_command(depth: int, ratio: float) -> str:
    rec = next(r for r in BUDGET["depths"] if r["depth"] == depth)
    return f"""# Execute ONLY on the named NVIDIA CUDA host after official Gate H passes.
# Do not run this command on the Mac. Do not pass --target-param-data-ratio=-1.
source scripts/p1/env.sh
cd "$P1_ROOT/vendor/nanochat"
export OMP_NUM_THREADS=1
# Set DEVICE_BATCH on the GPU host; start at 8 and halve until VRAM fits.
# Preserve --total-batch-size={rec["total_batch_size"]} via gradient accumulation.

python -m scripts.base_train \\
  --device-type=cuda \\
  --depth={depth} \\
  --max-seq-len=2048 \\
  --device-batch-size=${{DEVICE_BATCH}} \\
  --total-batch-size={rec["total_batch_size"]} \\
  --num-iterations={rec["num_iterations"]} \\
  --target-param-data-ratio={ratio} \\
  --eval-tokens={BUDGET["recommended_overrides_not_executed"]["eval_tokens"]} \\
  --eval-every=50 \\
  --core-metric-every=-1 \\
  --sample-every=200 \\
  --save-every=200 \\
  --warmup-steps={BUDGET["recommended_overrides_not_executed"]["warmup_steps"]} \\
  --run=p1-fixed-d{depth}-3x \\
  --model-tag=p1-fixed-d{depth}-3x
"""


def mac_dryrun_command(depth: int, ratio: float) -> str:
    return f"""# Non-confirmatory Mac MPS one-step dry run. confirmatory_eligible=false.
source scripts/p1/env.sh
cd "$P1_ROOT/vendor/nanochat"
unset PYTORCH_ENABLE_MPS_FALLBACK
export OMP_NUM_THREADS=1

python -m scripts.base_train \\
  --device-type=mps \\
  --depth={depth} \\
  --max-seq-len=2048 \\
  --device-batch-size=1 \\
  --total-batch-size=2048 \\
  --num-iterations=1 \\
  --target-param-data-ratio={ratio} \\
  --eval-every=-1 \\
  --eval-tokens=2048 \\
  --core-metric-every=-1 \\
  --sample-every=-1 \\
  --save-every=1 \\
  --warmup-steps=1 \\
  --run=dummy \\
  --model-tag=p1-m4-mps-gatei-preflight-d{depth}
"""


def confirmatory_card(detail: dict) -> str:
    d = detail["depth"]
    rec = next(r for r in BUDGET["depths"] if r["depth"] == d)
    ratio = rec["target_param_data_ratio"]
    return f"""# Confirmatory run card — `p1-fixed-d{d}-3x`

- Generated by: `scripts/p1/generate_gate_i_runcards.py`
- Generated at (UTC): {utc_now()}
- Do not hand-edit. Re-generate from `manifests/budget_manifest.json`.
- Protocol: P1.1 / AsPredicted #306780
- Parent RUN_ID: `{RUN_ID}`
- Status: **prepared, not executed**
- `confirmatory_eligible`: true **only after** official Gate H passes on a named NVIDIA CUDA host
- `platform` at execution: `nvidia-cuda` (not this Mac)

## Frozen quantities

| Field | Value |
|---|---|
| Depth | {d} |
| `n_embd` / `n_head` | {detail["n_embd"]} / {detail["n_head"]} |
| `window_pattern` | {detail["window_pattern"]} |
| `max-seq-len` | 2048 |
| `P_total` | {rec["p_total"]} |
| `P_scaling` | {rec["p_scaling"]} |
| `target_param_data_ratio` (`R_d`) | {ratio} |
| `total_batch_size` | {rec["total_batch_size"]} |
| `num_iterations` | {rec["num_iterations"]} |
| `D_3x` | {BUDGET["d_3x"]} |
| `D_actual` | {rec["d_actual"]} |
| Tokenizer SHA-256 | `{TOKENIZER["hashes"]["tokenizer.pkl"]}` |
| Train split SHA-256 | `{SPLIT["file_sha256"]["train"]}` |
| nanochat commit | `{NANOCHAT_COMMIT}` |
| `model_tag` / checkpoint dir | `p1-fixed-d{d}-3x` |
| `selection_rule` | `exact_minimum_final_val_bpb_full` |
| `evaluation_checkpoint_rule` | `final_checkpoint_at_fixed_budget` |
| `test_selection_source` | `validation_only` |
| `checkpoint_step` | {rec["num_iterations"]} |

## Command (NVIDIA only)

```bash
{confirmatory_command(d, ratio).rstrip()}
```

## Hard rules

- Never pass `--target-param-data-ratio=-1`.
- Never shrink `T=2048` to fit VRAM; shrink `--device-batch-size` only.
- Never change `--total-batch-size` or `--num-iterations` without a dated deviation card.
- Do not read the test split. `test_bpb` happens once after validation-only `D*` selection.
- Mid-run val-best checkpoints are diagnostic only.
"""


def mac_card(detail: dict) -> str:
    d = detail["depth"]
    rec = next(r for r in BUDGET["depths"] if r["depth"] == d)
    ratio = rec["target_param_data_ratio"]
    return f"""# Mac MPS Gate I infrastructure preflight — d{d}

- Generated by: `scripts/p1/generate_gate_i_runcards.py`
- Generated at (UTC): {utc_now()}
- Parent classification: `docs/run-cards/deviations/2026-08-16-mac-mps-gatei-infrastructure.md`
- `platform`: `macos-mps`
- `purpose`: `gate_i_infrastructure_preflight`
- `confirmatory_eligible`: **false**
- `model_tag`: `p1-m4-mps-gatei-preflight-d{d}`

This one-step dry run may test instantiation, paths, checkpoint naming, save, and reload at `T=2048`.
It must not be compared to other depths and must not enter the confirmatory table.

Mac dry-run `total_batch_size=2048` and `num_iterations=1` are **not** the frozen confirmatory budget
(`B={rec["total_batch_size"]}`, `N={rec["num_iterations"]}`, `D_actual={rec["d_actual"]}`).

```bash
{mac_dryrun_command(d, ratio).rstrip()}
```

If this depth OOMs at `T=2048` on the Mac, record the OOM. Do not shrink `T`.
"""


def main() -> int:
    details = {row["depth"]: row for row in BUDGET["depth_details"]}
    matrix = {
        "study_id": "NANOCHAT-FILIPINO-P1.1",
        "parent_run_id": RUN_ID,
        "generated_at_utc": utc_now(),
        "generated_by": "scripts/p1/generate_gate_i_runcards.py",
        "source_budget": "manifests/budget_manifest.json",
        "official_gate_i_started": False,
        "confirmatory_host_required": "named_nvidia_cuda",
        "gpu_host_for_H_I": None,
        "selection_rule": "exact_minimum_final_val_bpb_full",
        "evaluation_checkpoint_rule": "final_checkpoint_at_fixed_budget",
        "test_selection_source": "validation_only",
        "never_target_param_data_ratio_minus_one": True,
        "sequence_length": 2048,
        "d_3x": BUDGET["d_3x"],
        "common_total_batch_size": BUDGET["common_total_batch_size"],
        "num_iterations": BUDGET["num_iterations"],
        "d_actual": BUDGET["d_actual"],
        "runs": [],
        "mac_preflight_runs": [],
    }
    hashes = {}
    for depth in (8, 12, 16, 20):
        detail = details[depth]
        rec = next(r for r in BUDGET["depths"] if r["depth"] == depth)
        conf_path = OUT_DIR / f"p1-fixed-d{depth}-3x.md"
        mac_path = OUT_DIR / f"preflight-macos-mps-d{depth}.md"
        hashes[str(conf_path.relative_to(ROOT))] = write(conf_path, confirmatory_card(detail))
        hashes[str(mac_path.relative_to(ROOT))] = write(mac_path, mac_card(detail))
        matrix["runs"].append(
            {
                "run_name": f"p1-fixed-d{depth}-3x",
                "depth": depth,
                "status": "prepared_not_executed",
                "confirmatory_eligible": True,
                "platform": "nvidia-cuda",
                "model_tag": f"p1-fixed-d{depth}-3x",
                "checkpoint_dir": f"data/cache/{RUN_ID}/base_checkpoints/p1-fixed-d{depth}-3x",
                "p_total": rec["p_total"],
                "p_scaling": rec["p_scaling"],
                "target_param_data_ratio": rec["target_param_data_ratio"],
                "total_batch_size": rec["total_batch_size"],
                "num_iterations": rec["num_iterations"],
                "d_actual": rec["d_actual"],
                "max_seq_len": 2048,
                "run_card": str(conf_path.relative_to(ROOT)),
            }
        )
        matrix["mac_preflight_runs"].append(
            {
                "run_name": f"p1-m4-mps-gatei-preflight-d{depth}",
                "depth": depth,
                "status": "prepared_not_executed",
                "confirmatory_eligible": False,
                "platform": "macos-mps",
                "purpose": "gate_i_infrastructure_preflight",
                "model_tag": f"p1-m4-mps-gatei-preflight-d{depth}",
                "total_batch_size": 2048,
                "num_iterations": 1,
                "max_seq_len": 2048,
                "run_card": str(mac_path.relative_to(ROOT)),
            }
        )
    commands = ["#!/usr/bin/env bash", "# Generated. Confirmatory commands are NVIDIA-only.", ""]
    for depth in (8, 12, 16, 20):
        rec = next(r for r in BUDGET["depths"] if r["depth"] == depth)
        commands.append(f"# --- confirmatory d{depth} (NVIDIA only) ---")
        commands.append(confirmatory_command(depth, rec["target_param_data_ratio"]))
        commands.append(f"# --- mac preflight d{depth} (non-confirmatory) ---")
        commands.append(mac_dryrun_command(depth, rec["target_param_data_ratio"]))
    hashes["docs/run-cards/gate-i/COMMANDS.generated.sh"] = write(
        OUT_DIR / "COMMANDS.generated.sh", "\n".join(commands)
    )
    matrix["card_sha256"] = hashes
    matrix_path = ROOT / "manifests" / "gate_i_run_matrix.json"
    text = json.dumps(matrix, indent=2) + "\n"
    matrix_path.write_text(text, encoding="utf-8")
    print(json.dumps({"ok": True, "matrix": str(matrix_path.relative_to(ROOT)), "cards": hashes}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
